apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'

android {
    namespace "es.soutullo.blitter"
    compileSdkVersion 36
    defaultConfig {
        applicationId "es.soutullo.blitter"
        minSdkVersion 23
        targetSdkVersion 36
        versionCode 11
        versionName "2.2.1"
        multiDexEnabled true
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    buildFeatures {
        aidl true
        dataBinding true
    }
    applicationVariants.all { variant ->
        variant.resValue "string", "app_version_name", variant.versionName
    }
}

dependencies {
    implementation 'com.google.firebase:firebase-ads:11.8.0'
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    androidTestImplementation('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    implementation "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"

    implementation 'com.android.support:appcompat-v7:26.1.0'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    implementation 'com.android.support:design:26.1.0'
    implementation 'com.google.android.gms:play-services-vision:11.8.0'
    implementation 'com.google.android.gms:play-services-ads:11.8.0'
    implementation 'com.android.support:preference-v7:26.1.0'
    implementation 'com.github.sevar83:indeterminate-checkbox:1.0.5@aar'
    implementation 'com.github.apl-devs:appintro:v4.2.2'
    implementation 'com.github.kobakei:MaterialFabSpeedDial:1.1.5'
    implementation('com.github.woxingxiao:BubbleSeekBar:3.20') {
        exclude group: 'com.android.support'
    }
    implementation 'com.bignerdranch.android:recyclerview-multiselect:0.2'
    testImplementation 'junit:junit:4.12'
}

apply plugin: 'kotlin-kapt'

repositories {
    mavenCentral()
}

apply plugin: 'com.google.gms.google-services'
