#!/usr/bin/env python3
"""
Create a local draft for consumable support products from exported remove-ads products.

This script does not call Google Play APIs. It reads the JSON exported by
export_play_products.py and writes a draft payload that can be reviewed before
any catalog changes are made.
"""

from __future__ import annotations

import argparse
import copy
import json
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


SUPPORT_PRODUCT_IDS = {
    "es.soutullo.blitter.product.removeads": "es.soutullo.blitter.product.support.coffee",
    "es.soutullo.blitter.product.removeads.soda": "es.soutullo.blitter.product.support.soda",
    "es.soutullo.blitter.product.removeads.basicmeal": "es.soutullo.blitter.product.support.basicmeal",
    "es.soutullo.blitter.product.removeads.nicemeal": "es.soutullo.blitter.product.support.nicemeal",
    "es.soutullo.blitter.product.removeads.cry": "es.soutullo.blitter.product.support.cry",
}

TITLE_PREFIX_BY_LANGUAGE = {
    "en": "Support Blitter",
    "es": "Apoyar Blitter",
    "gl": "Apoiar Blitter",
    "pt": "Apoiar o Blitter",
}

DESCRIPTION_BY_LANGUAGE = {
    "en": "Extra donation to support Blitter. This does not unlock any additional benefit.",
    "es": "Donación extra para apoyar Blitter. No desbloquea ningún beneficio adicional.",
    "gl": "Doazón extra para apoiar Blitter. Non desbloquea ningún beneficio adicional.",
    "pt": "Doação extra para apoiar o Blitter. Isto não desbloqueia nenhum benefício adicional.",
}

LABEL_REGEX = re.compile(r"\(([^)]+)\)")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Draft support product definitions from exported remove-ads products."
    )
    parser.add_argument("catalog", help="Path to JSON generated by export_play_products.py.")
    parser.add_argument(
        "--output",
        default="build/reports/play-products/support-products-draft.json",
        help="Draft output path.",
    )
    return parser.parse_args()


def language_family(language_code: str) -> str:
    return language_code.split("-", maxsplit=1)[0]


def localized_title(language_code: str, source_title: str) -> str:
    family = language_family(language_code)
    prefix = TITLE_PREFIX_BY_LANGUAGE.get(family, TITLE_PREFIX_BY_LANGUAGE["en"])
    match = LABEL_REGEX.search(source_title)
    label = match.group(1).strip() if match else source_title.strip()

    return f"{prefix} ({label})"


def localized_description(language_code: str) -> str:
    family = language_family(language_code)
    return DESCRIPTION_BY_LANGUAGE.get(family, DESCRIPTION_BY_LANGUAGE["en"])


def to_support_product(product: dict[str, Any]) -> dict[str, Any]:
    source_product_id = product["productId"]
    support_product = copy.deepcopy(product)
    support_product["sourceProductId"] = source_product_id
    support_product["sourceRegionsVersion"] = support_product.get("regionsVersion")
    support_product["productId"] = SUPPORT_PRODUCT_IDS[source_product_id]

    support_product.pop("regionsVersion", None)

    for purchase_option in support_product.get("purchaseOptions", []):
        purchase_option["sourcePurchaseOptionId"] = purchase_option.get("purchaseOptionId")
        purchase_option["purchaseOptionId"] = "support-base"

    for listing in support_product.get("listings", []):
        listing["title"] = localized_title(listing["languageCode"], listing["title"])
        listing["description"] = localized_description(listing["languageCode"])

    return support_product


def load_remove_ads_products(catalog_path: Path) -> list[dict[str, Any]]:
    catalog = json.loads(catalog_path.read_text(encoding="utf-8"))
    products = catalog["apis"]["onetimeproducts"]["products"]

    return [
        product
        for product in products
        if product.get("productId") in SUPPORT_PRODUCT_IDS
    ]


def write_output(output_path: Path, payload: dict[str, Any]) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


def print_summary(payload: dict[str, Any]) -> None:
    print(f"Output: {payload['outputPath']}")

    for product in payload["products"]:
        options = product.get("purchaseOptions", [])
        regions = options[0].get("regionalPricingAndAvailabilityConfigs", []) if options else []
        print(f"- {product['productId']}")
        print(f"  source: {product['sourceProductId']}")
        print(f"  listings: {len(product.get('listings', []))}")
        print(f"  regions: {len(regions)}")


def main() -> int:
    args = parse_args()
    catalog_path = Path(args.catalog)
    output_path = Path(args.output)

    products = load_remove_ads_products(catalog_path)
    draft_products = [
        to_support_product(product)
        for product in sorted(products, key=lambda item: item["productId"])
    ]

    payload = {
        "createdAt": datetime.now(timezone.utc).isoformat(),
        "sourceCatalog": str(catalog_path),
        "outputPath": str(output_path),
        "products": draft_products,
    }

    write_output(output_path, payload)
    print_summary(payload)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
